/*
	This software is licenced under the GNU General Purpose Licence 3.0 . see http://www.gnu.org/licenses/gpl-3.0.txt
	Copyright (C) 2014 Xavier "dascritch" Mouton-Dubosc
 */
(function(document, window, browser) {
	'use strict';

	/**
	 * Important notice : this code should be able to run in any recent and decent browser.
	 * I coded it as strictly independant from Firefox, so you can re-use it
	 */

	var LAYOUT_ID = 'anchors-reveal';
	var LAYOUT_Z_INDEX = 2147483647; // 2^31-1 , theorical maximum 
	var THEMES = {
		'ClassicalYellow' : {
			background : 'yellow',
			color : 'black'
		},
		'LightBlue'  : {
			background : '#aaf',
			color : 'black'
		},
		'WhitePaper' : {
			background : 'white',
			color : 'black'
		},
		'GothicAddict' : {
			background : 'black',
			color : 'white'
		},
	}

	var theme = THEMES['ClassicalYellow'];
	var valid_id = /^[a-zA-Z0-9\-\_\.]+$/;

	function build_layer() {
	

		function reveal_for_element(element) {
			var id = element.id || element.name;
			if (
				element.dataset.anchors_reveal === undefined // not generated by the addon ?
				&& valid_id.test(id) // not malicious ?
			) {
				var rect = element.getBoundingClientRect();
				var x = rect.left + window.scrollX;
				var y = rect.top + window.scrollY;
				if ( ! ( (x === 0) && (y === 0) )) {
                	// not on top, and really visible
					var tag = document.createElement('a');
                    tag.className = LAYOUT_ID;
					tag.dataset.anchors_reveal = true;
					tag.href = '#'+id;
					tag.style.left = x+'px';
					tag.style.top = y+'px';
					tag.appendChild( document.createTextNode('#'+id) );
					layout.appendChild(tag);
					has = true;
				}
			}
		}

		var layout = document.createElement('div');
		layout.id = LAYOUT_ID;
		layout.dataset.anchors_reveal = true;
		layout.style = `position : absolute;
				top : 0px;
				left : 0px;
				margin : 0px;
				padding : 0px;
				border : none;
				width : ${document.body.scrollWidth}px;
				height : ${document.body.scrollHeight}px;
				overflow : hidden;
				z-index : ${LAYOUT_Z_INDEX};   
				pointer-events : none;`;
		document.body.appendChild(layout);

		var style = document.createElement('style');
		style.scoped = true;
		style.appendChild( document.createTextNode(`
				a.${LAYOUT_ID} {
					position : absolute ;
					font-family : sans-serif ;
					font-size : 14px ;
					font-weight : bold;
					background : ${theme.background} ;
					color : ${theme.color};
					padding : 4px ;
					border : 1px black solid ;
					opacity : 0.7 ;
					pointer-events : auto;
				}
				a.${LAYOUT_ID}:hover {
					opacity : 1 ;
					color : black;
				}`));
		layout.appendChild(style);

		var has = false;
		Array.from(document.querySelectorAll('[id], a[name]')).
			forEach(reveal_for_element);
		if (!has) {
			console.alert('Unnamed puppy : Not a single ID element in this page. Bad dog, no biscuit.');
		}
	}

	function destroy() {
        window.removeEventListener('resize', destroy, false);
		var container = document.getElementById(LAYOUT_ID);
        if (container) {
            document.body.removeChild(container);
        } else {
           console.log('Failed to find container');
        }
	}

	function on_error(error) {
	  	console.log(`Error: ${error}`);
	}

/*
	function on_got_sidebar(result) {
	  	if (result.sidebar) {
	    	// TODO open sidebar

	  	}
	  	build_layer();
	}
*/

	function on_got_parameters(result) {
	  	if (result.theme) {
	    	theme = THEMES[result.theme];
	  	}
	  	//var getting_storage = browser.storage.local.get('sidebar');
		//getting_storage.then(on_got_sidebar, on_error);
		build_layer();
	}

	if (document.getElementById(LAYOUT_ID) === null) {
		var getting_storage = browser.storage.local.get('theme');
		getting_storage.then(on_got_parameters, on_error);
	} else {
		destroy();
	}


	window.addEventListener('resize', destroy, false);
})(document, window, browser);
